# Generated by Django 5.0.6 on 2024-07-01 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='duration_field',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AddField(
            model_name='doctor',
            name='today_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
