# Generated by Django 5.0.6 on 2024-07-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_doctor_duration_field_doctor_today_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='duration_field',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='today_date',
        ),
        migrations.AddField(
            model_name='doctor',
            name='favorite_food',
            field=models.CharField(choices=[('pasta', 'pasta'), ('udon', 'udon'), ('pizza', 'pizza')], default='pasta', max_length=20),
        ),
    ]
